project:
  type: website

website:
  title: "GTPS"
  sidebar:
    style: "floating"
    search: false
    contents:
      - href: "index.qmd"
      - section: "GTP 0"
        contents:
          - GTP0/gtp0.qmd
      - section: "GTP 1"
        contents:
          - GTP1/gtp1.qmd
format:
  html:
    theme: cosmo
    toc: true
    code-copy: true